### ISSUE TITLE
ContentDB release

### ISSUE THREAD

**Issue by S-S-X** [mt-mods/wrench#1]
Add ContentDB mod package.

There probably should be specific note that crafting is allowed by default when there's suitable materials for crafting and that tool is considered to be safe and supported for regular player use.
(if dependencies stay all optional then there might not be suitable recipes included)

Link to https://github.com/mt-mods/technic/issues/253
It would be very good to make ContentDB release with Technic ContentDB release after cleanup and other v2.x work is done in Technic modpack.

**Comment by BuckarooBanzay** [comment]
I've prepared the package here: https://content.minetest.net/packages/mt-mods/wrench/
Open issues:
* [x] License: i only found the LGPLv2.1+
* [x] Maintainers: did i get everybody?
* [x] Readme, screenshots, etc

**Comment by wsor4035** [comment]
re: maintainers
im not there, but doesn't really matter

**Comment by S-S-X** [comment]
> I've prepared the package here: https://content.minetest.net/packages/mt-mods/wrench/

Also ContentDB release can very well be done before Technic v2 release, more important is that package is available before wrench is removed from Technic.

**Comment by OgelGames** [comment]
Oh, this can be close now :)
