### ISSUE TITLE
[Related Mod] Teleporter Tool

### ISSUE THREAD

**Issue by ApolloX939** [mt-mods/wrench#10]
Isn't this mod related to [teleporter_tool](https://content.minetest.net/packages/ApolloX/teleporter_tool/)?

It's neat to see a different concept/implementation of the same general idea.

**Comment by ApolloX939** [comment]
An no wait, I see now teleporter_tool doesn't handle "active" nodes (so things like furnaces would break on teleport).

**Comment by OgelGames** [comment]
The key difference is that the teleporter tool **moves** nodes, and the wrench **picks up** nodes.
