### ISSUE TITLE
Picking up bones in protected areas

### ISSUE THREAD

**Issue by MCLV-pandorabox** [mt-mods/wrench#14]
It would save me some work to be able to pick up expired bones boxes from deceased players.
Their bones would already be neatly packaged for when they want to come and pick them up and I don't get their items confused with whatever is in my inventory. And I could do all pickups in 1 go

**Comment by SwissalpS** [comment]
It's possibly non-trivial as [bones_redo] bones don't have a fixed size inventory if they are using inventory at all.

I totally support the idea, have wished for it myself.

**Comment by SwissalpS** [comment]
@OgelGames was that the issue? What about giving bones an insanely huge inventory? Then it would be fixed size and would also allow viewing contents again.

**Comment by OgelGames** [comment]
It's already possible to pick up fresh and old bones :)

**Comment by SwissalpS** [comment]
> It's already possible to pick up fresh and old bones :)

That must have happened very recently, because I only just tried and failed a few weeks ago.

**Comment by SwissalpS** [comment]
Just got test report from pandorabox:
```
<FeXoR> "Cannot pickup node, Owned by Jisilion"
<Jisilion> Can't pick up my bones with a wrench: "This area is owned by FeXoR"
<Jisilion> Uhm, sorry, didn't test old bones :/
```

**Comment by OgelGames** [comment]
Still sounds like correct behavior to me, you shouldn't be able to pick up fresh bones of another player.

But maybe the other case could be improved, you should be able to pick up your own bones from an area protected by another player. Actually, that's what the main issue is here, protection should be ignored when picking up bones.

**Comment by SwissalpS** [comment]
In my test case, the area was mine and the bones were old and still I wasn't able to pick them up.

**Comment by MCLV-pandorabox** [comment]
Since expired bones can be picked up by anyone regardless of protection area, I think the correct behavior would be to be able to pick up expired bones with the wrench. With this logic, it does not incur on any other aspects of game play I think.

Except for people like me, who like to pick up other peoples bones for safe storage and pickup. (like mentioned before)

But currently the wrench checks the owner field and refuses to pick them up since they owner doesn't match(ignoring the fact that the bones are expired)
